# requiring the environment of Ruby 2.5.x
image: ruby:2.5

# add cache to 'vendor' for speeding up builds
cache:
  paths: 
    - vendor/

before_script:
  - export LC_ALL="C.UTF-8"
  - export LANG="en_US.UTF-8"
  - export LANGUAGE="en_US.UTF-8"
  - bundle install --path vendor

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - main # this job will affect only the 'main' branch
